language: python

matrix:
    include:

        - python: 3.6
          dist: xenial
          sudo: true


install:
    - pip install -r requirements.txt


script:
    - python -c 'from tobacco_litigation.testing import run_doctests_travis; run_doctests_travis()'